- build: 0.23.0/centos/7
  image:
    - mesoscloud/mesos-master:0.23.0-centos-7
    - mesoscloud/mesos-master:0.23.0-centos
    - mesoscloud/mesos-master:0.23.0
    - mesoscloud/mesos-master:latest

- build: 0.23.0/ubuntu/14.04
  image:
    - mesoscloud/mesos-master:0.23.0-ubuntu-14.04
    - mesoscloud/mesos-master:0.23.0-ubuntu

- build: 0.22.1/centos/7
  image:
    - mesoscloud/mesos-master:0.22.1-centos-7
    - mesoscloud/mesos-master:0.22.1-centos
    - mesoscloud/mesos-master:0.22.1

- build: 0.22.1/ubuntu/14.04
  image:
    - mesoscloud/mesos-master:0.22.1-ubuntu-14.04
    - mesoscloud/mesos-master:0.22.1-ubuntu


- tests:
    - cmd: mesos-master --version

    - cmd: test -z "`echo $MESOS_AUTHENTICATE`"

    - cmd: test "`echo $MESOS_AUTHENTICATE`" = true
      env:
        - SECRET=password
