- build: 0.22.1/centos/7
  image:
    - mesoscloud/mesos-master:0.22.1-centos-7
    - mesoscloud/mesos-master:0.22.1-centos
    - mesoscloud/mesos-master:0.22.1
    - mesoscloud/mesos-master:latest
    
- build: 0.22.1/ubuntu/14.04
  image:
    - mesoscloud/mesos-master:0.22.1-ubuntu-14.04
    - mesoscloud/mesos-master:0.22.1-ubuntu
